INSERT INTO GAME_CONFIGURATION VALUES ('REVERSII', 8,8, 50, 2, 2);


INSERT INTO PLAYER_TYPE VALUES('AI');
INSERT INTO PLAYER_TYPE VALUES('HUMAN');

INSERT INTO IDENTIFIER VALUES('BLACK');
INSERT INTO IDENTIFIER VALUES('WHITE');
